---
- name: Install HAProxy
  ansible.builtin.apt:
    name: 
      - haproxy
    state: present
    update_cache: yes

- name: Configure HAProxy
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify:
   - Restart haproxy

- name: Ensure HAProxy is running
  service:
    name: haproxy
    state: started