docker_registry_enabled: false
loadbalancer_enabled: true
packages_repositiry_enabled: true
create_default_storage_on_all_devices: false
create_default_mds: false
create_default_rgw: false
#ntp_server_source: 100.125.0.31 # put NTP server source to confgigure it during validation step