---
# TODO configure self-signed certeficate, which later easily can be changed by real cert
- name: Install HAProxy
  package:
    name: haproxy
    state: present

- name: Configure HAProxy with SSL/TLS passthrough
  template:
    src: haproxy_ssl.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: '0644'
  notify:
    - Restart HAProxy

- name: Ensure HAProxy is enabled and running
  service:
    name: haproxy
    state: started
    enabled: true

- name: Change Standby Behaviour when loadbalancer enabled
  command: ceph config set mgr mgr/dashboard/standby_behaviour "error"
  delegate_to: "{{ groups['admin'][0] }}"

- name: Info
  debug:
    msg: |
      Ceph Dashboard available on the url: https://{{ ansible_host }}
      Username: admin
      Password: admin007 (you will have to change during first login)