---
- name: Validate system requirements
  hosts: all
  tasks:

    - name: Check for Python 3
      command: python3 --version
      register: python3_check
      ignore_errors: yes

    - name: Validate Python 3 Installation
      debug:
        msg: "Python 3 is installed: {{ python3_check.stdout }}"
      when: python3_check.rc == 0

    - name: Check for systemd
      stat:
        path: /usr/lib/systemd/systemd
      register: systemd_check

    - name: Validate systemd Availability
      debug:
        msg: "Systemd is available"
      when: systemd_check.stat.exists

    - name: Check for chrony or ntpd
      shell: |
        if systemctl is-active --quiet chronyd.service; then
          echo "Chrony is active"
        elif systemctl is-active --quiet ntpd.service; then
          echo "NTP is active"
        else
          exit 1
        fi
      register: time_sync_check
      ignore_errors: yes

    - name: Validate Time Synchronization
      debug:
        msg: "{{ time_sync_check.stdout }}"
      when: time_sync_check.rc == 0

# add Time synchronization integrating task

    - name: Check if LVM2 is installed
      command: rpm -q lvm2
      register: lvm_check
      ignore_errors: yes

    - name: Install LVM2
      package:
        name: lvm2
        state: present
      when: lvm_check.rc != 0

    - name: Check for Podman or Docker
      shell: |
        if command -v podman; then
          echo "Podman is installed"
        elif command -v docker; then
          echo "Docker is installed"
        else
          exit 1
        fi
      register: podman_docker_check
      ignore_errors: yes
      changed_when: podman_docker_check.rc != 0

    - name: Install Podman
      package:
        name: podman
        state: present
        update_cache: yes
      when: podman_docker_check.rc != 0

# TODO enable and configure firewalld