---
- name: Setup Docker Registry on Admin Host
  hosts: docker_registry
  become: yes
  tasks:
    - name: Ensure /opt/registry/{auth,certs,data} directories exist
      file:
        path: /opt/registry/{{ item }}
        state: directory
        mode: '0755' 
      loop:
        - auth
        - certs
        - data

    - name: Run Docker registry using Podman
      shell: |
        podman load -i docker_archives/registry_2.8.3.tar || true
        podman run --privileged -d --name registry -p 5000:5000 -v /opt/registry/data:/var/lib/registry --restart=always registry:2.8.3
      args:
        chdir: "{{ playbook_dir }}"
      register: mon_ip
      ignore_errors: yes

    # - name: Run Docker registry using Podman
    #   community.general.podman_container:
    #     name: registry
    #     image: registry:2
    #     state: started
    #     detach: true
    #     privileged: true
    #     ports:
    #       - "5000:5000"
    #     volume:
    #       - "/var/lib/registry:/var/lib/registry"
    #     restart_policy: always

    - name: Configure registries.conf
      blockinfile:
        path: /etc/containers/registries.conf
        block: |
          [[registry]]
          prefix = "{{ ansible_host }}:5000"
          location = "{{ ansible_host }}:5000"
          insecure = true
        insertafter: EOF
      register: config_result

    - name: Copy registries.conf to all hosts
      copy:
        src: /etc/containers/registries.conf
        dest: /etc/containers/registries.conf
      delegate_to: "{{ item }}"
      with_items: "{{ groups['all'] }}"
      run_once: true
      when: config_result.changed

    - name: Restart Podman to apply configuration changes
      service:
        name: podman
        state: restarted

    - name:
      debug:
        msg: | 
          Dir is "{{ playbook_dir }}"
          ./upload_images.sh groups['docker_registry'][0]:5000

    - name: Uploading downloaded .tar docker image into private registry {{ groups['docker_registry'][0] }}:5000
      shell: |
        ./upload_images.sh {{ groups['docker_registry'][0] }}:5000
      args:
        chdir: "{{ playbook_dir }}"
      delegate_to: 127.0.0.1

# TODO configure ssl, authorization