[mgr]
mgr/cephadm/container_image_prometheus = 10.1.195.23:5000/prometheus:v2.51.0
mgr/cephadm/container_image_node_exporter = 10.1.195.23:5000/node_exporter:v1.7.0
mgr/cephadm/container_image_grafana = 10.1.195.23:5000/grafana:10.4.0
mgr/cephadm/container_image_alertmanager = 10.1.195.23:5000/alertmanger:v0.25.0
