[mgr]
mgr/cephadm/container_image_prometheus = 10.1.195.23:5000/prometheus:v2.51.0
mgr/cephadm/container_image_node_exporter = 10.1.195.23:5000/node-exporter:v1.7.0
mgr/cephadm/container_image_grafana = 10.1.195.23:5000/grafana:10.4.0
mgr/cephadm/container_image_alertmanager = 10.1.195.23:5000/alertmanager:v0.25.0
[global]
container_image = 10.1.195.23:5000/ceph/:v19.2.0
#quay.io/ceph/haproxy:2.3
#quay.io/ceph/keepalived:2.2.4