[mgr]
mgr/cephadm/container_image_prometheus = 10.1.195.23:5000/prometheus
mgr/cephadm/container_image_node_exporter = 10.1.195.23:5000/node_exporter
mgr/cephadm/container_image_grafana = 10.1.195.23:5000/grafana
mgr/cephadm/container_image_alertmanager = 10.1.195.23:5000/alertmanger
